Vagrant.configure("2") do |config|
	# Jenkins Server Configuration
	config.vm.define "jenkins-server" do |jenkins|
		jenkins.vm.box = "ubuntu/jammy64"
		jenkins.vm.hostname = "jenkins-server"
	
		# Port forwarding for Jenkins web interface
		jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
		
		# Disable the default shared folder to work with WSL
		jenkins.vm.synced_folder ".", "/vagrant", disabled: true
		
		jenkins.vm.provider "virtualbox" do |vb|
			vb.name = "jenkins-server"
			vb.memory = "2048"
			vb.cpus = 2
			
			# WSL compatibility fixes
			vb.customize ["modifyvm", :id, "--uart1", "off"]
			vb.customize ["modifyvm", :id, "--uart2", "off"]
			vb.customize ["modifyvm", :id, "--uart3", "off"]
			vb.customize ["modifyvm", :id, "--uart4", "off"]
		end
		jenkins.vm.provision "shell", path: "jenkins-install.sh", privileged: true
	end

	# Ubuntu Server Configuration
	config.vm.define "ubuntu-server" do |ubuntu|
		ubuntu.vm.box = "ubuntu/jammy64"
		ubuntu.vm.hostname = "ubuntu-server"
		ubuntu.vm.network "private_network", ip: "192.168.56.10"
		ubuntu.vm.synced_folder ".", "/vagrant", disabled: true

		ubuntu.vm.provider "virtualbox" do |vb|
			vb.name = "ubuntu-server"
			vb.memory = 1024
			vb.cpus = 1
			vb.customize ["modifyvm", :id, "--uart1", "off"]
			vb.customize ["modifyvm", :id, "--uart2", "off"]
			vb.customize ["modifyvm", :id, "--uart3", "off"]
			vb.customize ["modifyvm", :id, "--uart4", "off"]
		end
	end
end